const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const R=path.resolve(__dirname,'..'),context={window:{}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(R,'Statcal','stats-data.js'),'utf8'),context);const D=context.window.STAT_DATA;
const E=require('../Statcal/stats-engine.js').make(D);
const manualDefaults=()=>({...E.defaults(),autoEffects:false});
const char=id=>Object.keys(D.maps.characters).find(k=>D.maps.characters[k]===String(id));
const slot=id=>({character:char(id),artifact:null,legendMonster:null,equipment:{hat:null,top:null,gloves:null,shoes:null},rings:{ring1:[null,null,null,null],ring2:[null,null,null,null],ring3:[null,null,null,null]},ringMonsters:{ring1:null,ring2:null,ring3:null}});
const party={slots:[slot(101901),slot(104001),slot(101401)]},d=manualDefaults();
let r=E.calculate(party,d);assert.equal(r.slots[0].values.crit,5);assert.equal(r.slots[0].values.ice||0,0);
d.slots[1].effects['1:skill-104007']={on:true,stacks:1};r=E.calculate(party,d);for(const s of r.slots)assert.equal(s.values.atk,20,'summer attack applies to every party member');
d.slots[2].effects['2:skill-101406']={on:true};r=E.calculate(party,d);assert.equal(r.slots[0].values.ice,50);assert.equal(r.slots[2].values.ice,50);assert.equal(r.slots[1].values.earth||0,0,'ice effect must not leak to earth');
d.slots[2].canto=4;d.slots[2].effects['2:skill-101435']={on:true};r=E.calculate(party,d);assert.equal(r.slots[0].values.ice,E.compile(101435,4).deltas[0].value);
d.slots[1].canto=6;d.slots[1].effects['1:skill-104009']={on:true};r=E.calculate(party,d);assert.equal(r.slots[0].values.atk,E.compile(104009,6).deltas[0].value,'enhanced buff replaces base buff');
d.slots[1].effects['1:skill-104003']={on:true,stacks:99};r=E.calculate(party,d);assert.equal(r.slots[0].values.boss,E.compile(104003).deltas[0].value*3,'stack cap');
const f=manualDefaults();f.foodMain='51111';r=E.calculate(party,f);for(const s of r.slots)assert.equal(s.values.hp,11,'party-wide food HP');
const t=manualDefaults();t.slots[0].ring.ring1.values[0]=50;party.slots[0].ringMonsters.ring1=Object.keys(D.maps.monsters)[0];party.slots[0].rings.ring1[0]='trait_incap_dmg';t.slots[0].effects['0:skill-101928']={on:true};r=E.calculate(party,t);assert.ok(Math.abs(r.slots[0].values.atk-1.95)<1e-9,'prime 7.5% groggy × 26% conversion = 1.95% ATK');
const sanitized=E.sanitize({slots:[{canto:100,level:-4,effects:{x:{on:'true',stacks:Infinity}},equipment:{hat:{crit:999}}}]});assert.equal(sanitized.slots[0].canto,6);assert.equal(sanitized.slots[0].level,60);assert.equal(sanitized.slots[0].equipment.hat.crit,999);assert.equal(sanitized.slots[0].effects.x.on,false);assert.equal(E.sanitize(null).foodMain,null);
// Exercise existing PNG codec without needing DOM or a browser.
const app=fs.readFileSync(path.join(R,'app.js'),'utf8'),start=app.indexOf('const PARTY_PNG_KEYWORD'),end=app.indexOf('// 지금 파티 상태');
const codec={TextEncoder,TextDecoder,Uint8Array,Uint32Array,DataView,ArrayBuffer,console};vm.createContext(codec);vm.runInContext(app.slice(start,end)+';globalThis.codec={embedPartyDataInPng,extractPartyDataFromPng};',codec);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3ioAAAAASUVORK5CYII=','base64');
for(const payload of [{app:'mongil-stardive-party',schema:1,slots:party.slots},{app:'mongil-stardive-party',schema:1,slots:party.slots,detailedStats:d}]){const json=JSON.stringify(payload),b=codec.codec.embedPartyDataInPng(png.buffer.slice(png.byteOffset,png.byteOffset+png.byteLength),json);assert.equal(codec.codec.extractPartyDataFromPng(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)),json);}
const fixed=manualDefaults();party.slots[0].equipment.gloves='test-selected';fixed.slots[0].equipment.gloves={atk:200,crit:120,critDmg:400};let before=E.calculate(party,manualDefaults()).slots[0];r=E.calculate(party,fixed);assert.equal(r.slots[0].values.atkFlat-before.values.atkFlat,200,'equipment ATK is flat, not percentage');assert.equal(r.slots[0].values.atk,before.values.atk);assert.equal(r.slots[0].values.crit,100);assert.equal(r.slots[0].excess.crit,25);assert.equal(r.slots[0].values.critDmg,300);assert.equal(r.slots[0].excess.critDmg,150);assert.equal(D.equipmentMax.gloves.value,846);assert.equal(D.equipmentMax.gloves.level,18);
const prime=manualDefaults();party.slots[0].rings.ring1[0]='trait_crit_dmg';prime.slots[0].ring.ring1.grade=1;prime.slots[0].ring.ring1.values[0]=999;let primeResult=E.calculate(party,prime);assert.equal(primeResult.slots[0].values.critDmg,65,'selected prime option automatically adds 15%, ignoring manual values');assert.equal(primeResult.detail.slots[0].ring.ring1.grade,5);party.slots[0].legendMonster=Object.keys(D.maps.legends)[0];prime.slots[0].legend.types[0]='trait_crit_dmg';primeResult=E.calculate(party,prime);assert.equal(primeResult.slots[0].values.critDmg,80,'legend prime crit damage is automatic');assert.ok(D.foodImages['51111']);
console.log('PASS: buffs, conversions, PNG round-trip, flat equipment, caps, automatic prime and legend options, food icon mapping');
const penetration=manualDefaults();penetration.slots[0].effects['0:skill-101938']={on:true};assert.equal(E.calculate(party,penetration).slots[0].values.penetration,15,'energy 100 activates 15% penetration');penetration.slots[0].canto=6;penetration.slots[0].effects['0:skill-101952']={on:true};assert.equal(E.calculate(party,penetration).slots[0].values.penetration,32.89,'canto 6 penetration stacks with energy effect');

const automatic=E.defaults();automatic.slots[1].canto=2;automatic.slots[2].canto=4;automatic.slots[1].effects['1:skill-104007']={on:false};const ar=E.calculate(party,automatic);assert.ok(ar.slots[0].values.atk>=20,'party ATK auto applies despite old off checkbox');assert.ok(ar.slots[1].values.earth>=40,'earth character receives earth buff');assert.ok(ar.slots[0].values.ice>=90,'ice character receives Nara ice buff');assert.equal(ar.slots[0].values.earth||0,0,'earth buff excludes ice character');const se=ar.effects.find(e=>e.gid===104003);assert.equal(se.appliedStacks,3,'automatic effects use max stacks');console.log('PASS: automatic activation, legacy off-state ignored, elemental target filtering, max stacks');
