(function(){
 'use strict';
 const engine=MongilStatsEngine.make(STAT_DATA),E=engine;
 for(const [key,list] of Object.entries({characters:CHARACTERS,monsters:MONSTERS,artifacts:ARTIFACTS,legends:LEGEND_MONSTERS}))for(const item of STAT_DATA.additions[key]||[])if(!list.some(x=>x.id===item.id))list.push(item);
 let detail=E.defaults(),active=false,selectedCharacter=0;
 const area=document.getElementById('detailEditor'),container=document.getElementById('detailSlots');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:2});
 const options=(values,value)=>values.map(([v,label])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(label)}</option>`).join('');
 const levels=(a,b)=>Array.from({length:b-a+1},(_,i)=>[i+a,i+a]);
 const input=(label,path,value,min=0,max=1000,step='.1')=>`<label class="detail-field"><span>${esc(label)}</span><input data-detail-path="${path}" type="number" min="${min}" max="${max}" step="${step}" value="${path.includes('.equipment.')&&!Number(value)?'':Number(value)||0}" ${path.includes('.equipment.')?'placeholder="숫자 입력해주세요"':''} inputmode="decimal"></label>`;
 const select=(label,path,value,values)=>`<label class="detail-field"><span>${esc(label)}</span><select data-detail-path="${path}">${options(values,value)}</select></label>`;
 function foodLabel(id){const item=E.T.ITEM_LIST[id];return item?`${item.RARE_GRADE}등급 · ${E.loc(item.ITEM_NAME_LOCAL).startsWith('특별한 ')?'대성공':'일반'}`:'요리 선택 +';}
 function foodItems(kind){const groups=new Map();for(const [id,item] of Object.entries(E.T.ITEM_LIST)){if(item.ITEM_TYPE!==41)continue;const buffs=E.by('BOOSTER','BOOSTER_GROUP',Number(id));if(!buffs.some(b=>b.BUFF_ICON?.AssetPathName?.includes(kind==='foodMain'?'_main_':'_dessert_')))continue;if(buffs.every(b=>/부활|회복/.test(E.description(b.BOOSTER_DESC,b.BOOSTER_DESC_PARAM))))continue;const name=foodLabel(id);if(!groups.has(name))groups.set(name,{id,name,image:STAT_DATA.foodImages?.[id]||'assets/placeholder.svg'});}return [...groups.values()].sort((a,b)=>E.T.ITEM_LIST[b.id].RARE_GRADE-E.T.ITEM_LIST[a.id].RARE_GRADE||Number(a.id)-Number(b.id));}
 function foodText(id){if(!id)return '선택 안 함';return E.by('BOOSTER','BOOSTER_GROUP',Number(id)).map(b=>E.description(b.BOOSTER_DESC,b.BOOSTER_DESC_PARAM)).join(' · ');}
 function refresh(){if(!active)return;detail=E.shared(state,detail);const calculation=E.calculate(state,detail);renderFoods();container.innerHTML=`<nav class="detail-character-tabs">${state.slots.map((s,i)=>`<button type="button" data-detail-character="${i}" class="${i===selectedCharacter?'is-active':''}">${i+1} · ${esc(findById(CHARACTERS,s.character)?.name||'캐릭터 선택')}</button>`).join('')}</nav>`;
  state.slots.forEach((s,i)=>{const q=detail.slots[i],c=E.character(s.character),row=document.createElement('section');row.className='detail-character'+(i===selectedCharacter?' is-current':'');row.dataset.detailIndex=i;
   const card=document.createElement('div');card.className='detail-selection';card.appendChild(renderSlot(s,i));const portraitImage=card.querySelector('.char-card__portrait img');if(portraitImage){const portrait=portraitImage.parentElement;portrait.style.backgroundImage='url('+JSON.stringify(portraitImage.src)+')';portrait.setAttribute('role','img');portrait.setAttribute('aria-label',portraitImage.alt);portraitImage.remove();}decorateMonsterOptions(card,s,i);row.appendChild(card);
   const controls=document.createElement('div');controls.className='detail-controls';
   controls.innerHTML=`<header class="detail-section-heading"><div><h2>${esc(findById(CHARACTERS,s.character)?.name||'캐릭터를 선택하세요')}</h2><p>캐릭터·아티팩트 60레벨 / 레벨 돌파 완료</p></div></header><div class="detail-grid detail-growth">${select('캐릭터 돌파',`slots.${i}.canto`,q.canto,levels(0,6))}${select('아티팩트 결합',`slots.${i}.overlap`,q.overlap,levels(1,5))}${select('속성의 성소',`slots.${i}.sanctuary`,q.sanctuary,levels(0,50))}</div><h3>장비 옵션 <small>5등급 18강 주옵션 자동 적용</small></h3><div class="detail-equipment"><div class="detail-equipment-head"><span>부위</span><span>공격력 (상수)</span><span>치확 %</span><span>치피 %</span></div>${EQUIP_KEYS.map(k=>{const z=q.equipment[k]||{};return `<div class="detail-equipment-row"><strong>${esc(EQUIPMENT_LABELS[k].replace('장비 ',''))}</strong>${['atk','crit','critDmg'].map(f=>input('',`slots.${i}.equipment.${k}.${f}`,z[f]||0,0,f==='atk'?100000:10000,f==='atk'?'1':'.1')).join('')}</div>`;}).join('')}</div>`;
   row.appendChild(controls);const results=document.createElement('div');results.className='detail-results';results.innerHTML=renderResults(calculation.slots[i],i,c);row.appendChild(results);container.appendChild(row);
  });renderEffects(calculation);
 }
 function decorateMonsterOptions(card,s,i){
  const rings=card.querySelector('.rings'),q=detail.slots[i];
  const legendRow=document.createElement('div');legendRow.className='ring-row detail-legend-row';
  const label=document.createElement('button');label.type='button';label.className='ring-row__label';label.dataset.action='legend-monster';label.dataset.slotIndex=i;const legend=findById(LEGEND_MONSTERS,s.legendMonster);label.innerHTML=`<small>전설 · 프라임</small>${legend?`<img class="ring-row__monster-icon" src="${esc(imgOrPlaceholder(legend.image))}" alt="${esc(legend.name)}"><span class="ring-row__monster-name">${esc(legend.name)}</span>`:'<span>전설 몬스터링 선택 +</span>'}`;legendRow.appendChild(label);
  for(let j=0;j<4;j++){const button=document.createElement('button');button.type='button';button.className='ring-slot'+(q.legend.types[j]?' filled':'');button.dataset.legendOption=j;button.dataset.slotIndex=i;const option=findById(TRAIT_OPTIONS,q.legend.types[j]);const stat=E.primeOption(q.legend.types[j],E.card(s.legendMonster,'legends',5));button.innerHTML=`<span class="ring-slot__value">${esc(option?.name||'옵션 '+(j+1)+' 선택 +')}</span>${stat?`<small class="detail-prime-value">${fmt(stat.value)}%</small>`:''}`;legendRow.appendChild(button);}rings.prepend(legendRow);
  card.querySelectorAll('.ring-slot[data-ring]').forEach(cell=>{const rk=cell.dataset.ring,j=Number(cell.dataset.optIndex),option=E.primeOption(s.rings[rk][j],E.card(s.ringMonsters[rk],'monsters',5));if(option){const value=document.createElement('small');value.className='detail-prime-value';value.textContent=fmt(option.value)+'%';cell.appendChild(value);}});
 }
 function renderFoods(){const box=document.getElementById('detailFoods');box.innerHTML=`<div class="detail-food-label"><span class="detail-eyebrow">PARTY EFFECT</span><h2>파티 공통 요리</h2><p>세 캐릭터에게 동일하게 적용됩니다.</p></div>${['foodMain','foodSide'].map((f,i)=>`<div class="detail-food"><button type="button" data-food="${f}"><small>${i?'사이드 요리':'메인 요리'}</small>${detail[f]&&STAT_DATA.foodImages?.[detail[f]]?`<img class="detail-food-image" src="${esc(STAT_DATA.foodImages[detail[f]])}" alt="">`:""}<strong>${esc(detail[f]?foodLabel(detail[f]):'요리 선택 +')}</strong></button><p>${esc(foodText(detail[f]))}</p></div>`).join('')}`;}
 function renderResults(r,i,c){const elm=E.elements[r.element],items=[['공격력',r.atk,false],['공격력 증가',r.values.atk,true,'atk'],['치명타 확률',r.values.crit,true,'crit'],['치명타 피해',r.values.critDmg,true,'critDmg'],['관통률',r.values.penetration,true,'penetration'],['궁극 스킬 충전율',r.values.ultimateGauge,true,'ultimateGauge'],[E.names[elm]||'주속성 피해',r.values[elm],true,elm],['제압 피해',r.values.suppress,true,'suppress'],['무력화 피해',r.values.groggy,true,'groggy'],['약점 속성 피해',r.values.weakness,true,'weakness'],['보스 몬스터 피해',r.values.boss,true,'boss'],['지원 피해',r.values.support,true,'support'],['난전 피해',r.values.brawl,true,'brawl'],['일반 몬스터 피해',r.values.normal,true,'normal'],['특수 스킬 쿨타임 감소',r.values.cooldown,true,'cooldown'],...['basicDamage','specialDamage','ultimateDamage','tagDamage','specialAtk','damageReduction'].filter(k=>r.values[k]).map(k=>[E.names[k],r.values[k],true,k])];
  return `<header><span class="detail-eyebrow">LIVE STATS</span><h2>전투 중 적용 스탯</h2><p>${r.selected?'조건부 효과 발동 · 최대 중첩 기준':'캐릭터 선택 후 계산됩니다.'}</p></header><dl>${items.map(([name,value,pct,key])=>`<div><dt>${esc(name)}${r.caps?.[key]!=null?`<small class="detail-cap">상한 ${fmt(r.caps[key])}%</small>`:''}</dt><dd>${r.selected?fmt(value)+(pct?'%':''):'—'}${r.excess?.[key]>0?`<small class="detail-excess">초과 +${fmt(r.excess[key])}%</small>`:''}</dd></div>`).join('')}</dl><details><summary>적용 출처 ${r.logs.length}개</summary><ul>${r.logs.map(l=>`<li><span>${esc(l.label)} · ${esc(E.names[l.key]||l.key)}</span><b>+${fmt(l.value)}</b></li>`).join('')}</ul></details>${r.warnings.length?`<details class="detail-warning" open><summary>계산에 포함하지 못한 항목 ${r.warnings.length}개</summary><ul>${r.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:''}`;
 }
 function renderEffects(calc){const el=document.getElementById('detailEffects');el.innerHTML=`<header class="detail-effects-header"><div><h2>자동 적용 효과</h2><p>조건부 효과 발동 · 최대 중첩을 가정합니다. 캐릭터 속성과 돌파 단계를 확인해 적용하며 링크체인은 제외합니다.</p></div></header><div class="detail-effects-grid">${calc.effects.map(e=>`<article class="detail-effect ${e.unsupported?'is-unsupported':''}" data-auto-applied="${e.applied?'true':'false'}"><header class="detail-effect-title"><div class="detail-effect-name"><small>${e.owner+1}번 캐릭터 · ${esc(e.label)}</small><b>${esc(e.title)}</b></div><span class="detail-effect-badge">${e.unsupported?'계산 미지원':e.applied?'자동 적용':'속성 조건 불일치'}</span></header><p>${esc(e.text||'원본 설명 없음')}</p><div class="detail-effect-settings"><span>${e.applied?'적용: '+e.appliedTo.map(i=>esc(findById(CHARACTERS,state.slots[i].character)?.name||i+1+'번')).join(', '):e.targetElement?E.names[E.elements[e.targetElement]]+' 캐릭터만':'스탯 계산 제외'}${e.appliedStacks>1?' · 최대 '+e.appliedStacks+'중첩':''}</span></div>${e.scopeUnverified&&!e.unsupported?'<small class="detail-warning-text">적용 대상은 원본 설명 기준으로 판단</small>':''}${(e.remainder||[]).map(t=>`<small class="detail-warning-text">${esc(t)}</small>`).join('')}</article>`).join('')||'<p class="detail-empty">캐릭터와 장비를 선택하면 자동 적용 효과가 나타납니다.</p>'}</div>`;}
 function setPath(path,value){const match=path.match(/^slots\.(\d+)\.sanctuary$/);if(match){const elm=E.character(state.slots[Number(match[1])].character)?.ELEMENTAL_TYPE;if(elm)detail.sanctuaryLevels[elm]=Number(value);}let parts=path.split('.'),o=detail;for(const k of parts.slice(0,-1)){if(!o[k]||typeof o[k]!=='object')o[k]={};o=o[k];}o[parts.at(-1)]=value;}
 function refreshNumbers(){const calc=E.calculate(state,detail);container.querySelectorAll('.detail-results').forEach((el,i)=>{el.innerHTML=renderResults(calc.slots[i],i,E.character(state.slots[i].character));});}
 area.addEventListener('input',ev=>{const el=ev.target;if(el.dataset.detailPath&&el.type==='number'){setPath(el.dataset.detailPath,Number(el.value));detail=E.sanitize(detail);refreshNumbers();}});
 area.addEventListener('change',ev=>{const el=ev.target;if(el.dataset.detailPath){setPath(el.dataset.detailPath,el.type==='number'?Number(el.value):el.value);detail=E.sanitize(detail);refresh();}});
 document.getElementById('detailFoods').addEventListener('click',ev=>{const button=ev.target.closest('[data-food]');if(!button)return;const f=button.dataset.food;openModal({title:f==='foodMain'?'메인 요리':'사이드 요리',items:foodItems(f),onSelect:id=>{detail[f]=id;if(detail.foodMain&&detail.foodMain===detail.foodSide)detail[f==='foodMain'?'foodSide':'foodMain']=null;closeModal();refresh();},onClear:()=>{detail[f]=null;closeModal();refresh();}});});
 container.addEventListener('click',ev=>{const btn=ev.target.closest('[data-detail-character]');if(btn){selectedCharacter=Number(btn.dataset.detailCharacter);refresh();return;}const optionBtn=ev.target.closest('[data-legend-option]');if(optionBtn){const i=Number(optionBtn.dataset.slotIndex),j=Number(optionBtn.dataset.legendOption);openLegendOptions(i,j);return;}handleSlotClick(ev);});
 function openLegendOptions(i,start){const monster=state.slots[i].legendMonster;if(!monster)return;detail=E.shared(state,detail);let current=start;const arr=()=>detail.legendOptions[monster];const title=()=>{modalTitle.textContent='전설 몬스터링 옵션 선택 (옵션 '+(current+1)+')';};openModal({title:'전설 몬스터링 옵션 선택 (옵션 '+(current+1)+')',items:TRAIT_OPTIONS,getSelectedIds:()=>new Set(arr().filter(Boolean)),onSelect:id=>{const a=arr(),existing=a.indexOf(id);if(existing>=0){a[existing]=null;refresh();renderModalList(modalContext.items);return;}a[current]=id;refresh();const next=arr().findIndex(v=>v===null);if(next<0){closeModal();return;}current=next;title();modalSearch.value='';renderModalList(modalContext.items);modalSearch.focus();},onClear:()=>{arr()[current]=null;refresh();closeModal();}});}
 function switchTab(mode){active=mode==='detail';document.getElementById('slots').classList.toggle('hidden',active);area.classList.toggle('hidden',!active);document.querySelector('.brand__subtitle').textContent=active?'상세 스탯 에디터':'파티 에디터';document.querySelectorAll('[data-editor-tab]').forEach(el=>el.classList.toggle('is-active',el.dataset.editorTab===mode));document.getElementById('captureArea').classList.toggle('board--detail',active);refresh();}
 
 window.DetailedEditor={get active(){return active;},refresh,export:()=>E.shared(state,detail),import:raw=>{detail=E.sanitize({...raw,autoEffects:true});},calculate:()=>E.calculate(state,detail),engine:E,switchTab};
 try{const saved=sessionStorage.getItem('mongil-detail-restore');if(saved){sessionStorage.removeItem('mongil-detail-restore');applyImportedPartyPayload(saved);}}catch(e){}
 switchTab('detail');
})();

