const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'Statcal/stats-data.js'),'utf8'),ctx);
const D=ctx.window.STAT_DATA,E=require('../Statcal/stats-engine.js').make(D);
const blank=id=>({character:id,artifact:null,legendMonster:null,equipment:{shoes:'test-shoes'},rings:{ring1:[],ring2:[],ring3:[]},ringMonsters:{}});
const ids=Object.keys(D.maps.characters).filter(id=>E.character(id)),lines=['# 전체 캐릭터·아티팩트 계산 감사','', '2026-10-10. 원본 데이터와 계산 연결에 대한 자동 감사. 전체 실게임 동작 검증과는 구분한다.','', '## 캐릭터: 돌파 0~6 + 성소 0/40','', '|캐릭터|검증 조합|수집 효과 수 범위|','|---|---:|---:|'];
let count=0;
for(const id of ids){let sizes=[];for(let canto=0;canto<=6;canto++)for(const sanctuary of [0,40]){const p={slots:[blank(id),blank(id),blank(id)]},d=E.defaults();d.slots.forEach(q=>{q.canto=canto;q.sanctuary=sanctuary;});const r=E.calculate(p,d);sizes.push(r.effects.filter(e=>e.owner===0).length);for(const s of r.slots)for(const value of Object.values(s.values))assert.ok(Number.isFinite(value),id+' finite output');for(const e of r.effects)for(const to of e.appliedTo){if(e.targetElement)assert.equal(r.slots[to].element,e.targetElement);if(e.excludeElement)assert.notEqual(r.slots[to].element,e.excludeElement);if(e.targetRange)assert.equal(E.character(p.slots[to].character).RANGE_TYPE,e.targetRange);}count++;}lines.push('|'+E.character(id).REF_NAME+'|14|'+Math.min(...sizes)+'~'+Math.max(...sizes)+'|');}
lines.push('','## 아티팩트: 결합 1~5 / 같은 역할 / 신발 장착','','|아티팩트|검증 단계|일반 효과 노드|스탯 외 효과|','|---|---:|---:|---|');
let artifactCount=0;
for(const aid of Object.keys(D.maps.artifacts)){const raw=E.T.ITEM_CUBE[D.maps.artifacts[aid]];if(!raw)continue;const cid=ids.find(id=>E.character(id).STATUS_TYPE===raw.CLASS_TYPE);assert.ok(cid);let nodes=[],unsupported=false;for(let overlap=1;overlap<=5;overlap++){const p={slots:[blank(cid),blank(cid),blank(cid)]},d=E.defaults();d.slots.forEach(q=>q.canto=6);p.slots[0].artifact=aid;d.slots[0].overlap=overlap;const r=E.calculate(p,d);for(const s of r.slots)for(const value of Object.values(s.values))assert.ok(Number.isFinite(value),aid+' finite output');const o=E.rows('CUBE_OVERLAP').find(o=>o.CUBE_ID==D.maps.artifacts[aid]&&o.OVERLAP_LEVEL===overlap),native=E.artifactEffects(Number(D.maps.artifacts[aid]),o,d.slots[0]);nodes.push(native.length);unsupported ||= native.some(e=>e.unsupported);for(const threshold of [3,5])if(o['FUSION_VALUE_'+threshold])assert.equal(r.effects.some(e=>e.owner===0&&e.gid===o['FUSION_VALUE_'+threshold]),overlap>=threshold);for(const e of native)for(const delta of e.deltas)assert.ok(Number.isFinite(delta.value)&&delta.stacks>=1);artifactCount++;}lines.push('|'+E.loc(raw.ITEM_NAME_LOCAL)+'|5|'+Math.min(...nodes)+'~'+Math.max(...nodes)+'|'+(unsupported?'회복/보호막/자원 등은 스탯 합산 제외':'')+'|');}
lines.push('','## 수정 및 확인','', '- 나래 얼음 팀원: 얼음 피해50%와 특수 피해30% 동시 적용. 돌파4에서는90%/60%. 얼음 외 원거리 특수 피해80%→150%.', '- 초원을 수놓은 이슬 결합3: 모든 팀원 기본 공격18%; 얼음 팀원 추가 기본 공격30% 및 치피37.5%.', '- 아티팩트 일반 효과를 설명문 전체에서 합산하던 방식 대신 능력 노드로 계산한다. 개별 효과 중첩·공격력 감소·기본/특수/궁극/교체 피해·궁극 충전·원소 피해·전환을 분리한다.', '- 생명의 두리별 자기 궁극 피해와 팀 공격력을 분리한다. 서머 프란시스 아티팩트의 땅 팀원 기본 공격, 영원의 피날레의 불 팀원 치피를 분리한다.', '- 미래를 여는 열쇠의 치피50% 초과분 전환은 원본 PARAM_5를 공제한다.', '', '## 감사 한계', '', '전 캐릭터의 돌파/성소 조합에서 계산 실행·조건 불일치·유한 수치를 확인했다. 전 아티팩트의5개 결합 단계와 원본 수치 연결을 확인했다. 이것만으로 미해석 능력 코드, 모든 전투 타이밍/서로 배타적인 상태, 모든 조건 적용 대상을 실게임과 같다고 인증할 수는 없다. 회복·보호막 효율·적 디버프·즉시 자원 충전은 현재 캐릭터 스탯 합산 범위 밖이다. 새로운 스탯 차이는 원본과 게임 실측을 대조해야 한다.');
lines.push('', '원본 캐릭터 미연결 항목: '+Object.entries(E.T.CHARACTER_LIST).filter(([id])=>!new Set(Object.values(D.maps.characters).map(Number)).has(Number(id))).map(([id,c])=>c.REF_NAME+'('+id+')').join(', '));
fs.writeFileSync(path.join(root,'STAT_AUDIT.md'),lines.join('\n'));console.log('PASS: '+ids.length+' characters / '+count+' canto-sanctuary combinations; '+artifactCount+' artifact overlap cases. Report: STAT_AUDIT.md');
